# -*- coding: utf-8 -*-
"""mealy machine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqfjIzrK996POciuZxObT6SmyECzE2MA
"""

PROGRAM:9
WAP to implement mealy machine that calculate 1's complement as output corresponding
to the input as binary number.

def State_q0(i):
  if i=="0":
    globals()["State"]="q0"
    output_string.append("1")
  elif i=="1":
    globals()["State"]="q0"
    output_string.append("0")


State="q0"
input_string=input("Enter string in 0&1:")
output_string=[]
for i in input_string:
  match State:
    case"q0":
      State_q0(i)
    case _:
      pass
print("Output string is:","".join(output_string))

"""PROGRAM:10
WAP to implement mealy machine that calculate 2's complement as output corresponding
to the input as binary number.
"""

def State_q0(i):
  if i=="0":
    globals()["State"]="q0"
    output_string.append("0")
  elif i=="1":
    globals()["State"]="q1"
    output_string.append("1")

def State_q1(i):
  if i=="0":
    globals()["State"]="q1"
    output_string.append("1")
  elif i=="1":
    globals()["State"]="q1"
    output_string.append("0")

State="q0"
input_string=input("Enter string in 0&1:")
input_string=input_string[::-1]
output_string=[]
for i in input_string:
  match State:
    case"q0":
      State_q0(i)
    case"q1":
      State_q1(i)
    case _:
      pass
output="".join(output_string)[::-1]
print("Output string is:",output)

"""PROGRAM 11 :
WAP to implement mealy machine that print 'E' for even number of a's & 'O' for odd number of a's.

"""

def State_q0(i):
  if i=="a":
    globals()["State"]="q1"
    output_string.append("O")
  elif i=="b":
    globals()["State"]="q0"
    output_string.append("E")


def State_q1(i):
  if i=="a":
    globals()["State"]="q0"
    output_string.append("E")
  elif i=="b":
    globals()["State"]="q1"
    output_string.append("O")

State="q0"
input_string=input("Enter string in a&b:")
output_string=[]
for i in input_string:
  match State:
    case"q0":
      State_q0(i)
    case"q1":
      State_q1(i)
    case _:
      pass
print("Output string is:","".join(output_string))

"""4-oct-2023"""

s="niharika"
if "niharika" in s:
  print("found")
else:
  print("not found")

import re

text='''Sagar Institute of Science and Technology (SISTec®), established in the year 2007, is one of the best engineering colleges, located in the heart of the state, the city of lakes - Bhopal. SISTec is the brand name for technical colleges under the umbrella of the Sagar Group of Institutions®. Boasting state-of-the-art facilities, a diverse student body, and a talented pool of faculty, SISTec has established itself as a leader in providing quality education offering B.Tech., MBA, and M.Tech. programs.'''
pat=r"[a]"
m=re.search(pat,text)
print(m)

text='''Sagar Institute of Science and Technology (SISTec®), established in the year 2007, is one of the best engineering colleges, located in the heart of the state, the city of lakes - Bhopal. SISTec is the brand name for technical colleges under the umbrella of the Sagar Group of Institutions®. Boasting state-of-the-art facilities, a diverse student body, and a talented pool of faculty, SISTec has established itself as a leader in providing quality education offering B.Tech., MBA, and M.Tech. programs.'''
pat=r"[a]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[bnhff]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[a-z A-Z]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[.]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[^a]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"[^a-z]",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"[^A-Za-z]",text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[^a]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

pat=r"[^a]"
m=re.search(pat,text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"[^A-Za-z]",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"[a-z]{4}",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"[e]{2}",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"a*",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"a+",text)
print(m)
if m:
    print("found")
else:
  print("not found")

m=re.search(r"ee+",text)
print(m)
if m:
    print("found")
else:
  print("not found")

mail_str='''from:onlinecourses@nptel.iitm.ac.in
to:	noc23-cs98-announce@nptel.iitm.ac.in
date:	3 Oct 2023, 12:59
mobile no:7089115259
subject:	Introduction To Machine Learning - Week 11 content is live now !!
mailing list:	noc23-cs98-announce@nptel.iitm.ac.in Filter messages from this mailing list
mailed-by:	nptel.iitm.ac.in
Signed by:	nptel-iitm-ac-in.20230601.gappssmtp.com
security:	 Standard encryption (TLS)'''
m=re.search(r"\d{10}",mail_str)
print(m)
if m:
    print("found")
else:
  print("not found")

mail_str='''from:onlinecourses@nptel.iitm.ac.in
to:	noc23-cs98-announce@nptel.iitm.ac.in
date:	3 Oct 2023, 12:59
mobile no:7089115259
subject:	Introduction To Machine Learning - Week 11 content is live now !!
mailing list:	noc23-cs98-announce@nptel.iitm.ac.in Filter messages from this mailing list
mailed-by:	nptel.iitm.ac.in
Signed by:	nptel-iitm-ac-in.20230601.gappssmtp.com
security:	 Standard encryption (TLS)'''
m=re.search(r"[\d{10}]",mail_str)
print(m)
if m:
    print("found")
else:
  print("not found")

mail_str='''email: niharikaninnoriya@gmail.com
from:onlinecourses@nptel.iitm.ac.in
to:	noc23-cs98-announce@nptel.iitm.ac.in
email: niharikaninnoriya@gmail.com
date:	3 Oct 2023, 12:59
mobile no:7089115259
subject:	Introduction To Machine Learning - Week 11 content is live now !!
mailing list:	noc23-cs98-announce@nptel.iitm.ac.in Filter messages from this mailing list
mailed-by:	nptel.iitm.ac.in
Signed by:	nptel-iitm-ac-in.20230601.gappssmtp.com
security:	 Standard encryption (TLS)'''
pat=r"\S+@\S+"
m=re.search(pat,mail_str)
print(m)
if m:
    print("found")
else:
  print("not found")

mail_str='''
from:onlinecourses@nptel.iitm.ac.in
to:	noc23-cs98-announce@nptel.iitm.ac.in
email: niharikaninnoriya@gmail.com
date:	3 Oct 2023, 12:59
mobile no:7089115259
subject:	Introduction To Machine Learning - Week 11 content is live now !!
mailing list:	noc23-cs98-announce@nptel.iitm.ac.in Filter messages from this mailing list
mailed-by:	nptel.iitm.ac.in
Signed by:	nptel-iitm-ac-in.20230601.gappssmtp.com
security:	 Standard encryption (TLS)'''
pat=r"\S+@\S+"
m=re.search(pat,mail_str)
print(m)
if m:
    print("found")
else:
  print("not found")

mail_str='''
from:onlinecourses@nptel.iitm.ac.in
to:	noc23-cs98-announce@nptel.iitm.ac.in
email: niharikaninnoriya@gmail.com
date:	03/09/2023, 12:59
mobile no:7089115259
subject:	Introduction To Machine Learning - Week 11 content is live now !!
mailing list:	noc23-cs98-announce@nptel.iitm.ac.in Filter messages from this mailing list
mailed-by:	nptel.iitm.ac.in
Signed by:	nptel-iitm-ac-in.20230601.gappssmtp.com
security:	 Standard encryption (TLS)'''
pat=r"\d{1,3}/\d{1,9}/\d{2,4}"
m=re.search(pat,mail_str)
print(m)
if m:
    print("found")
else:
  print("not found")